# Generated by Django 4.2.2 on 2024-02-13 03:09

import Myapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Myapp.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.TextField()),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to=Myapp.models.get_file_path)),
                ('Small_description', models.TextField(max_length=250)),
                ('Quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('Orignal_Price', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('Tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.TextField()),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.category')),
            ],
        ),
    ]
